# Generated by Django 5.2.1 on 2025-05-26 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_products_description_alter_products_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Categoría", "verbose_name_plural": "Categorías"},
        ),
        migrations.AlterModelOptions(
            name="products",
            options={"verbose_name": "Producto", "verbose_name_plural": "Productos"},
        ),
    ]
